#!/usr/bin/env python3
"""Sustained streaming soak-test client for V0.7 measurement.

Sends synthetic JPEG frames to a running Tower /ws endpoint at a target
FPS/resolution for a configured duration, then prints a Markdown report
combining the roadmap's documented targets with what this script observed
on the *sending* side.

Sends stream_start before the frame loop and stream_stop after it, so the
Tower's own [Tower][Session] final summary is bounded by this script's
actual streaming window rather than the WebSocket connection's lifetime.

This script cannot see the Tower's own CPU/RAM/backpressure/receive-side
metrics -- those are only visible in the Tower process's own log output
([Tower][Session] final summary: ...). Copy that log line into the printed
report's "Tower-side measured" section by hand.

Requires the `dev` extra: pip install -e ".[dev]"
"""
import argparse
import asyncio
import base64
import io
import json
import time

import websockets
from PIL import Image

ROADMAP_TARGET_WIDTH = 504
ROADMAP_TARGET_HEIGHT = 896
ROADMAP_TARGET_FPS = 15
ROADMAP_TARGET_MIN_MINUTES = 20
ROADMAP_TARGET_MAX_MINUTES = 30

# "synthetic-script": frames generated by this script -- lowest fidelity,
# validates Tower plumbing only. "mock-device-kit"/"iphone-camera": driven
# through the actual iOS app. "physical-glasses": real hardware end to end.
VALID_SOURCES = ("synthetic-script", "mock-device-kit", "iphone-camera", "physical-glasses")


def _make_jpeg_base64(width: int, height: int) -> str:
    buffer = io.BytesIO()
    Image.new("RGB", (width, height), color=(90, 90, 90)).save(buffer, format="JPEG")
    return base64.b64encode(buffer.getvalue()).decode("ascii")


async def run_soak_test(
    uri: str,
    width: int,
    height: int,
    fps: float,
    duration_s: float,
    source: str,
) -> dict:
    frame_data_b64 = _make_jpeg_base64(width, height)
    interval_s = 1.0 / fps
    seq = 0
    frames_sent = 0
    frames_acked = 0
    bytes_sent = 0
    start = time.perf_counter()

    async with websockets.connect(uri) as ws:
        await ws.send(json.dumps({"type": "stream_start"}))
        while (time.perf_counter() - start) < duration_s:
            frame_start = time.perf_counter()
            seq += 1
            payload = json.dumps(
                {
                    "type": "frame",
                    "seq": seq,
                    "width": width,
                    "height": height,
                    "format": "jpeg",
                    "data": frame_data_b64,
                }
            )
            await ws.send(payload)
            frames_sent += 1
            bytes_sent += len(payload)

            response = json.loads(await ws.recv())
            if response.get("type") == "frame_result":
                frames_acked += 1

            elapsed = time.perf_counter() - frame_start
            sleep_for = interval_s - elapsed
            if sleep_for > 0:
                await asyncio.sleep(sleep_for)

        await ws.send(json.dumps({"type": "stream_stop"}))

    elapsed_total = time.perf_counter() - start
    return {
        "source": source,
        "target_width": width,
        "target_height": height,
        "target_fps": fps,
        "requested_duration_s": duration_s,
        "actual_duration_s": round(elapsed_total, 2),
        "frames_sent": frames_sent,
        "frames_acked": frames_acked,
        "achieved_send_fps": round(frames_sent / elapsed_total, 2) if elapsed_total > 0 else 0.0,
        "bytes_sent": bytes_sent,
        "send_bandwidth_bps": round(bytes_sent / elapsed_total, 2) if elapsed_total > 0 else 0.0,
    }


def _print_report(result: dict) -> None:
    print("## V0.7 Sustained Streaming -- Soak Run Report\n")
    print(f"**Source:** {result['source']}\n")
    print("### Target (from 03-ROADMAP.md)")
    print(f"- Resolution: ~{ROADMAP_TARGET_WIDTH}x{ROADMAP_TARGET_HEIGHT}")
    print(f"- FPS: ~{ROADMAP_TARGET_FPS}")
    print(f"- Session duration: {ROADMAP_TARGET_MIN_MINUTES}-{ROADMAP_TARGET_MAX_MINUTES} minutes\n")
    print("### Measured -- client (send) side, this script")
    for key, value in result.items():
        if key == "source":
            continue
        print(f"- {key}: {value}")
    print(
        "\n### Measured -- Tower (receive/process) side\n"
        "Paste the Tower process's own log line here "
        "([Tower][Session] final summary: ...):\n\n"
        "```\n<paste here>\n```\n"
    )
    print(
        "### Manual (not measurable from this script or the Tower)\n"
        "- Battery behavior (iPhone):\n"
        "- Thermal behavior (iPhone/glasses):\n"
        "- Disconnects/anomalies observed during the run:\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--uri", default="ws://127.0.0.1:8000/ws")
    parser.add_argument("--width", type=int, default=ROADMAP_TARGET_WIDTH)
    parser.add_argument("--height", type=int, default=ROADMAP_TARGET_HEIGHT)
    parser.add_argument("--fps", type=float, default=ROADMAP_TARGET_FPS)
    parser.add_argument(
        "--duration-s",
        type=float,
        default=60.0,
        help=(
            "Soak duration in seconds (use e.g. 1200-1800 for the full "
            "20-30 minute roadmap target; defaults to a short 60s smoke run)."
        ),
    )
    parser.add_argument(
        "--source",
        required=True,
        choices=VALID_SOURCES,
        help="What produced the frames sent by this run, so the report cannot be mistaken for a different source.",
    )
    args = parser.parse_args()

    result = asyncio.run(
        run_soak_test(
            uri=args.uri,
            width=args.width,
            height=args.height,
            fps=args.fps,
            duration_s=args.duration_s,
            source=args.source,
        )
    )
    _print_report(result)


if __name__ == "__main__":
    main()
